// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: agent_conversations.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createAgentConversation = `-- name: CreateAgentConversation :one
INSERT INTO agent_conversations (client_id, user_id, azure_conversation_id)
VALUES ($1, $2, $3)
RETURNING id, created_at, updated_at, client_id, user_id, azure_conversation_id
`

type CreateAgentConversationParams struct {
	ClientID            uuid.NullUUID  `json:"client_id"`
	UserID              uuid.NullUUID  `json:"user_id"`
	AzureConversationID sql.NullString `json:"azure_conversation_id"`
}

func (q *Queries) CreateAgentConversation(ctx context.Context, arg CreateAgentConversationParams) (AgentConversation, error) {
	row := q.db.QueryRowContext(ctx, createAgentConversation, arg.ClientID, arg.UserID, arg.AzureConversationID)
	var i AgentConversation
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClientID,
		&i.UserID,
		&i.AzureConversationID,
	)
	return i, err
}

const createAgentConversationMessage = `-- name: CreateAgentConversationMessage :one
INSERT INTO agent_conversation_messages (conversation_id, speaker, message)
VALUES ($1, $2, $3)
RETURNING id, created_at, updated_at, conversation_id, speaker, message
`

type CreateAgentConversationMessageParams struct {
	ConversationID uuid.UUID `json:"conversation_id"`
	Speaker        string    `json:"speaker"`
	Message        string    `json:"message"`
}

func (q *Queries) CreateAgentConversationMessage(ctx context.Context, arg CreateAgentConversationMessageParams) (AgentConversationMessage, error) {
	row := q.db.QueryRowContext(ctx, createAgentConversationMessage, arg.ConversationID, arg.Speaker, arg.Message)
	var i AgentConversationMessage
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ConversationID,
		&i.Speaker,
		&i.Message,
	)
	return i, err
}

const deleteAgentConversation = `-- name: DeleteAgentConversation :exec
DELETE FROM agent_conversations
WHERE id = $1
`

func (q *Queries) DeleteAgentConversation(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteAgentConversation, id)
	return err
}

const deleteAgentConversationMessages = `-- name: DeleteAgentConversationMessages :exec
DELETE FROM agent_conversation_messages
WHERE conversation_id = $1
`

func (q *Queries) DeleteAgentConversationMessages(ctx context.Context, conversationID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteAgentConversationMessages, conversationID)
	return err
}

const getAgentConversation = `-- name: GetAgentConversation :one
SELECT id, created_at, updated_at, client_id, user_id, azure_conversation_id
FROM agent_conversations
WHERE id = $1
`

func (q *Queries) GetAgentConversation(ctx context.Context, id uuid.UUID) (AgentConversation, error) {
	row := q.db.QueryRowContext(ctx, getAgentConversation, id)
	var i AgentConversation
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClientID,
		&i.UserID,
		&i.AzureConversationID,
	)
	return i, err
}

const listAgentConversationMessages = `-- name: ListAgentConversationMessages :many
SELECT id, created_at, updated_at, conversation_id, speaker, message
FROM agent_conversation_messages
WHERE conversation_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListAgentConversationMessages(ctx context.Context, conversationID uuid.UUID) ([]AgentConversationMessage, error) {
	rows, err := q.db.QueryContext(ctx, listAgentConversationMessages, conversationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AgentConversationMessage
	for rows.Next() {
		var i AgentConversationMessage
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ConversationID,
			&i.Speaker,
			&i.Message,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAgentConversations = `-- name: ListAgentConversations :many
SELECT id, created_at, updated_at, client_id, user_id, azure_conversation_id
FROM agent_conversations
ORDER BY updated_at DESC
`

func (q *Queries) ListAgentConversations(ctx context.Context) ([]AgentConversation, error) {
	rows, err := q.db.QueryContext(ctx, listAgentConversations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AgentConversation
	for rows.Next() {
		var i AgentConversation
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ClientID,
			&i.UserID,
			&i.AzureConversationID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAgentConversationsByClient = `-- name: ListAgentConversationsByClient :many
SELECT id, created_at, updated_at, client_id, user_id, azure_conversation_id
FROM agent_conversations
WHERE client_id = $1
ORDER BY updated_at DESC
`

func (q *Queries) ListAgentConversationsByClient(ctx context.Context, clientID uuid.NullUUID) ([]AgentConversation, error) {
	rows, err := q.db.QueryContext(ctx, listAgentConversationsByClient, clientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AgentConversation
	for rows.Next() {
		var i AgentConversation
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ClientID,
			&i.UserID,
			&i.AzureConversationID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAgentConversationsByUser = `-- name: ListAgentConversationsByUser :many
SELECT id, created_at, updated_at, client_id, user_id, azure_conversation_id
FROM agent_conversations
WHERE user_id = $1
ORDER BY updated_at DESC
`

func (q *Queries) ListAgentConversationsByUser(ctx context.Context, userID uuid.NullUUID) ([]AgentConversation, error) {
	rows, err := q.db.QueryContext(ctx, listAgentConversationsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AgentConversation
	for rows.Next() {
		var i AgentConversation
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ClientID,
			&i.UserID,
			&i.AzureConversationID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setAgentConversationAzureID = `-- name: SetAgentConversationAzureID :one
UPDATE agent_conversations
SET azure_conversation_id = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id, created_at, updated_at, client_id, user_id, azure_conversation_id
`

type SetAgentConversationAzureIDParams struct {
	ID                  uuid.UUID      `json:"id"`
	AzureConversationID sql.NullString `json:"azure_conversation_id"`
}

func (q *Queries) SetAgentConversationAzureID(ctx context.Context, arg SetAgentConversationAzureIDParams) (AgentConversation, error) {
	row := q.db.QueryRowContext(ctx, setAgentConversationAzureID, arg.ID, arg.AzureConversationID)
	var i AgentConversation
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClientID,
		&i.UserID,
		&i.AzureConversationID,
	)
	return i, err
}

const touchAgentConversation = `-- name: TouchAgentConversation :exec
UPDATE agent_conversations
SET updated_at = NOW()
WHERE id = $1
`

func (q *Queries) TouchAgentConversation(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, touchAgentConversation, id)
	return err
}
