// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: alerts.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countRecentAlerts = `-- name: CountRecentAlerts :one
SELECT COUNT(*)
FROM alerts
WHERE created_at >= NOW() - INTERVAL '24 hours'
`

func (q *Queries) CountRecentAlerts(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countRecentAlerts)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAlert = `-- name: CreateAlert :one
INSERT INTO alerts (user_id, client_id, contact_method, send_at, priority, law_change_id, message)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, created_at, updated_at, user_id, client_id, contact_method, send_at, priority, law_change_id, message
`

type CreateAlertParams struct {
	UserID        uuid.NullUUID `json:"user_id"`
	ClientID      uuid.NullUUID `json:"client_id"`
	ContactMethod string        `json:"contact_method"`
	SendAt        time.Time     `json:"send_at"`
	Priority      string        `json:"priority"`
	LawChangeID   uuid.NullUUID `json:"law_change_id"`
	Message       string        `json:"message"`
}

func (q *Queries) CreateAlert(ctx context.Context, arg CreateAlertParams) (Alert, error) {
	row := q.db.QueryRowContext(ctx, createAlert,
		arg.UserID,
		arg.ClientID,
		arg.ContactMethod,
		arg.SendAt,
		arg.Priority,
		arg.LawChangeID,
		arg.Message,
	)
	var i Alert
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.ClientID,
		&i.ContactMethod,
		&i.SendAt,
		&i.Priority,
		&i.LawChangeID,
		&i.Message,
	)
	return i, err
}

const deleteAlert = `-- name: DeleteAlert :exec
DELETE FROM alerts
WHERE id = $1
`

func (q *Queries) DeleteAlert(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteAlert, id)
	return err
}

const getAlert = `-- name: GetAlert :one
SELECT id, created_at, updated_at, user_id, client_id, contact_method, send_at, priority, law_change_id, message
FROM alerts
WHERE id = $1
`

func (q *Queries) GetAlert(ctx context.Context, id uuid.UUID) (Alert, error) {
	row := q.db.QueryRowContext(ctx, getAlert, id)
	var i Alert
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.ClientID,
		&i.ContactMethod,
		&i.SendAt,
		&i.Priority,
		&i.LawChangeID,
		&i.Message,
	)
	return i, err
}

const listAlertsForClient = `-- name: ListAlertsForClient :many
SELECT id, created_at, updated_at, user_id, client_id, contact_method, send_at, priority, law_change_id, message
FROM alerts
WHERE client_id = $1
ORDER BY send_at DESC
`

func (q *Queries) ListAlertsForClient(ctx context.Context, clientID uuid.NullUUID) ([]Alert, error) {
	rows, err := q.db.QueryContext(ctx, listAlertsForClient, clientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Alert
	for rows.Next() {
		var i Alert
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserID,
			&i.ClientID,
			&i.ContactMethod,
			&i.SendAt,
			&i.Priority,
			&i.LawChangeID,
			&i.Message,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAlertsForUser = `-- name: ListAlertsForUser :many
SELECT id, created_at, updated_at, user_id, client_id, contact_method, send_at, priority, law_change_id, message
FROM alerts
WHERE user_id = $1
ORDER BY send_at DESC
`

func (q *Queries) ListAlertsForUser(ctx context.Context, userID uuid.NullUUID) ([]Alert, error) {
	rows, err := q.db.QueryContext(ctx, listAlertsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Alert
	for rows.Next() {
		var i Alert
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserID,
			&i.ClientID,
			&i.ContactMethod,
			&i.SendAt,
			&i.Priority,
			&i.LawChangeID,
			&i.Message,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentAlerts = `-- name: ListRecentAlerts :many
SELECT id, created_at, updated_at, user_id, client_id, contact_method, send_at, priority, law_change_id, message
FROM alerts
WHERE created_at >= NOW() - INTERVAL '24 hours'
ORDER BY created_at DESC
`

func (q *Queries) ListRecentAlerts(ctx context.Context) ([]Alert, error) {
	rows, err := q.db.QueryContext(ctx, listRecentAlerts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Alert
	for rows.Next() {
		var i Alert
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserID,
			&i.ClientID,
			&i.ContactMethod,
			&i.SendAt,
			&i.Priority,
			&i.LawChangeID,
			&i.Message,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
