// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: client_metadatas.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const addClientKeyword = `-- name: AddClientKeyword :one
INSERT INTO client_metadatas (client_id, keyword)
VALUES ($1, $2)
ON CONFLICT (client_id, keyword) DO UPDATE SET updated_at = NOW()
RETURNING id, created_at, updated_at, client_id, keyword
`

type AddClientKeywordParams struct {
	ClientID uuid.UUID `json:"client_id"`
	Keyword  uuid.UUID `json:"keyword"`
}

func (q *Queries) AddClientKeyword(ctx context.Context, arg AddClientKeywordParams) (ClientMetadata, error) {
	row := q.db.QueryRowContext(ctx, addClientKeyword, arg.ClientID, arg.Keyword)
	var i ClientMetadata
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClientID,
		&i.Keyword,
	)
	return i, err
}

const listClientKeywords = `-- name: ListClientKeywords :many
SELECT client_metadatas.id, client_metadatas.created_at, client_metadatas.updated_at, client_metadatas.client_id, client_metadatas.keyword, keywords.name AS keyword_name
FROM client_metadatas
JOIN keywords ON keywords.id = client_metadatas.keyword
WHERE client_metadatas.client_id = $1
ORDER BY keywords.name ASC
`

type ListClientKeywordsRow struct {
	ID          uuid.UUID `json:"id"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
	ClientID    uuid.UUID `json:"client_id"`
	Keyword     uuid.UUID `json:"keyword"`
	KeywordName string    `json:"keyword_name"`
}

func (q *Queries) ListClientKeywords(ctx context.Context, clientID uuid.UUID) ([]ListClientKeywordsRow, error) {
	rows, err := q.db.QueryContext(ctx, listClientKeywords, clientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListClientKeywordsRow
	for rows.Next() {
		var i ListClientKeywordsRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ClientID,
			&i.Keyword,
			&i.KeywordName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listClientsByKeyword = `-- name: ListClientsByKeyword :many
SELECT clients.id, clients.created_at, clients.updated_at, clients.name, clients.icon
FROM client_metadatas
JOIN clients ON clients.id = client_metadatas.client_id
WHERE client_metadatas.keyword = $1
ORDER BY clients.name ASC
`

func (q *Queries) ListClientsByKeyword(ctx context.Context, keyword uuid.UUID) ([]Client, error) {
	rows, err := q.db.QueryContext(ctx, listClientsByKeyword, keyword)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Client
	for rows.Next() {
		var i Client
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Name,
			&i.Icon,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeAllClientKeywords = `-- name: RemoveAllClientKeywords :exec
DELETE FROM client_metadatas
WHERE client_id = $1
`

func (q *Queries) RemoveAllClientKeywords(ctx context.Context, clientID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, removeAllClientKeywords, clientID)
	return err
}

const removeClientKeyword = `-- name: RemoveClientKeyword :exec
DELETE FROM client_metadatas
WHERE client_id = $1 AND keyword = $2
`

type RemoveClientKeywordParams struct {
	ClientID uuid.UUID `json:"client_id"`
	Keyword  uuid.UUID `json:"keyword"`
}

func (q *Queries) RemoveClientKeyword(ctx context.Context, arg RemoveClientKeywordParams) error {
	_, err := q.db.ExecContext(ctx, removeClientKeyword, arg.ClientID, arg.Keyword)
	return err
}
