// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: clients.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createClient = `-- name: CreateClient :one
INSERT INTO clients (name, icon, user_id)
VALUES ($1, $2, $3)
RETURNING id, created_at, updated_at, name, icon, user_id
`

type CreateClientParams struct {
	Name   string         `json:"name"`
	Icon   sql.NullString `json:"icon"`
	UserID uuid.NullUUID  `json:"user_id"`
}

func (q *Queries) CreateClient(ctx context.Context, arg CreateClientParams) (Client, error) {
	row := q.db.QueryRowContext(ctx, createClient, arg.Name, arg.Icon, arg.UserID)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.Icon,
		&i.UserID,
	)
	return i, err
}

const deleteClient = `-- name: DeleteClient :exec
DELETE FROM clients
WHERE id = $1
`

func (q *Queries) DeleteClient(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteClient, id)
	return err
}

const getClient = `-- name: GetClient :one
SELECT id, created_at, updated_at, name, icon, user_id
FROM clients
WHERE id = $1
`

func (q *Queries) GetClient(ctx context.Context, id uuid.UUID) (Client, error) {
	row := q.db.QueryRowContext(ctx, getClient, id)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.Icon,
		&i.UserID,
	)
	return i, err
}

const listClients = `-- name: ListClients :many
SELECT id, created_at, updated_at, name, icon, user_id
FROM clients
ORDER BY name ASC
`

func (q *Queries) ListClients(ctx context.Context) ([]Client, error) {
	rows, err := q.db.QueryContext(ctx, listClients)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Client
	for rows.Next() {
		var i Client
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Name,
			&i.Icon,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listClientsByUser = `-- name: ListClientsByUser :many
SELECT id, created_at, updated_at, name, icon, user_id
FROM clients
WHERE user_id = $1
ORDER BY name ASC
`

func (q *Queries) ListClientsByUser(ctx context.Context, userID uuid.NullUUID) ([]Client, error) {
	rows, err := q.db.QueryContext(ctx, listClientsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Client
	for rows.Next() {
		var i Client
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Name,
			&i.Icon,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchClients = `-- name: SearchClients :many
SELECT id, created_at, updated_at, name, icon, user_id
FROM clients
WHERE name ILIKE '%' || $1 || '%'
ORDER BY name ASC
`

func (q *Queries) SearchClients(ctx context.Context, dollar_1 sql.NullString) ([]Client, error) {
	rows, err := q.db.QueryContext(ctx, searchClients, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Client
	for rows.Next() {
		var i Client
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Name,
			&i.Icon,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateClient = `-- name: UpdateClient :one
UPDATE clients
SET name = $2, icon = $3, updated_at = NOW()
WHERE id = $1
RETURNING id, created_at, updated_at, name, icon, user_id
`

type UpdateClientParams struct {
	ID   uuid.UUID      `json:"id"`
	Name string         `json:"name"`
	Icon sql.NullString `json:"icon"`
}

func (q *Queries) UpdateClient(ctx context.Context, arg UpdateClientParams) (Client, error) {
	row := q.db.QueryRowContext(ctx, updateClient, arg.ID, arg.Name, arg.Icon)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.Icon,
		&i.UserID,
	)
	return i, err
}
