// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: documents.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createDocument = `-- name: CreateDocument :one
INSERT INTO documents (citation, date_placed, date_replaced)
VALUES ($1, $2, $3)
RETURNING id, created_at, updated_at, citation, date_placed, date_replaced
`

type CreateDocumentParams struct {
	Citation     string       `json:"citation"`
	DatePlaced   sql.NullTime `json:"date_placed"`
	DateReplaced sql.NullTime `json:"date_replaced"`
}

func (q *Queries) CreateDocument(ctx context.Context, arg CreateDocumentParams) (Document, error) {
	row := q.db.QueryRowContext(ctx, createDocument, arg.Citation, arg.DatePlaced, arg.DateReplaced)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Citation,
		&i.DatePlaced,
		&i.DateReplaced,
	)
	return i, err
}

const deleteDocument = `-- name: DeleteDocument :exec
DELETE FROM documents
WHERE id = $1
`

func (q *Queries) DeleteDocument(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteDocument, id)
	return err
}

const getDocument = `-- name: GetDocument :one
SELECT id, created_at, updated_at, citation, date_placed, date_replaced
FROM documents
WHERE id = $1
`

func (q *Queries) GetDocument(ctx context.Context, id uuid.UUID) (Document, error) {
	row := q.db.QueryRowContext(ctx, getDocument, id)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Citation,
		&i.DatePlaced,
		&i.DateReplaced,
	)
	return i, err
}

const listActiveDocuments = `-- name: ListActiveDocuments :many
SELECT id, created_at, updated_at, citation, date_placed, date_replaced
FROM documents
WHERE date_replaced IS NULL
ORDER BY citation ASC
`

func (q *Queries) ListActiveDocuments(ctx context.Context) ([]Document, error) {
	rows, err := q.db.QueryContext(ctx, listActiveDocuments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Document
	for rows.Next() {
		var i Document
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Citation,
			&i.DatePlaced,
			&i.DateReplaced,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDocuments = `-- name: ListDocuments :many
SELECT id, created_at, updated_at, citation, date_placed, date_replaced
FROM documents
ORDER BY created_at DESC
`

func (q *Queries) ListDocuments(ctx context.Context) ([]Document, error) {
	rows, err := q.db.QueryContext(ctx, listDocuments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Document
	for rows.Next() {
		var i Document
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Citation,
			&i.DatePlaced,
			&i.DateReplaced,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markDocumentReplaced = `-- name: MarkDocumentReplaced :one
UPDATE documents
SET date_replaced = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, created_at, updated_at, citation, date_placed, date_replaced
`

type MarkDocumentReplacedParams struct {
	ID           uuid.UUID    `json:"id"`
	DateReplaced sql.NullTime `json:"date_replaced"`
}

func (q *Queries) MarkDocumentReplaced(ctx context.Context, arg MarkDocumentReplacedParams) (Document, error) {
	row := q.db.QueryRowContext(ctx, markDocumentReplaced, arg.ID, arg.DateReplaced)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Citation,
		&i.DatePlaced,
		&i.DateReplaced,
	)
	return i, err
}

const searchDocumentsByCitation = `-- name: SearchDocumentsByCitation :many
SELECT id, created_at, updated_at, citation, date_placed, date_replaced
FROM documents
WHERE citation ILIKE '%' || $1 || '%'
ORDER BY citation ASC
`

func (q *Queries) SearchDocumentsByCitation(ctx context.Context, dollar_1 sql.NullString) ([]Document, error) {
	rows, err := q.db.QueryContext(ctx, searchDocumentsByCitation, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Document
	for rows.Next() {
		var i Document
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Citation,
			&i.DatePlaced,
			&i.DateReplaced,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDocument = `-- name: UpdateDocument :one
UPDATE documents
SET citation = $2, date_placed = $3, date_replaced = $4, updated_at = NOW()
WHERE id = $1
RETURNING id, created_at, updated_at, citation, date_placed, date_replaced
`

type UpdateDocumentParams struct {
	ID           uuid.UUID    `json:"id"`
	Citation     string       `json:"citation"`
	DatePlaced   sql.NullTime `json:"date_placed"`
	DateReplaced sql.NullTime `json:"date_replaced"`
}

func (q *Queries) UpdateDocument(ctx context.Context, arg UpdateDocumentParams) (Document, error) {
	row := q.db.QueryRowContext(ctx, updateDocument,
		arg.ID,
		arg.Citation,
		arg.DatePlaced,
		arg.DateReplaced,
	)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Citation,
		&i.DatePlaced,
		&i.DateReplaced,
	)
	return i, err
}
