// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: document_revisions.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createDocumentRevision = `-- name: CreateDocumentRevision :one
INSERT INTO document_revisions (explanation, document_id_old, document_id_new, sub_document_id_old, sub_document_id_new)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, created_at, updated_at, explanation, document_id_old, document_id_new, sub_document_id_old, sub_document_id_new
`

type CreateDocumentRevisionParams struct {
	Explanation      string    `json:"explanation"`
	DocumentIDOld    uuid.UUID `json:"document_id_old"`
	DocumentIDNew    uuid.UUID `json:"document_id_new"`
	SubDocumentIDOld uuid.UUID `json:"sub_document_id_old"`
	SubDocumentIDNew uuid.UUID `json:"sub_document_id_new"`
}

func (q *Queries) CreateDocumentRevision(ctx context.Context, arg CreateDocumentRevisionParams) (DocumentRevision, error) {
	row := q.db.QueryRowContext(ctx, createDocumentRevision,
		arg.Explanation,
		arg.DocumentIDOld,
		arg.DocumentIDNew,
		arg.SubDocumentIDOld,
		arg.SubDocumentIDNew,
	)
	var i DocumentRevision
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Explanation,
		&i.DocumentIDOld,
		&i.DocumentIDNew,
		&i.SubDocumentIDOld,
		&i.SubDocumentIDNew,
	)
	return i, err
}

const deleteDocumentRevision = `-- name: DeleteDocumentRevision :exec
DELETE FROM document_revisions
WHERE id = $1
`

func (q *Queries) DeleteDocumentRevision(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteDocumentRevision, id)
	return err
}

const getDocumentRevision = `-- name: GetDocumentRevision :one
SELECT id, created_at, updated_at, explanation, document_id_old, document_id_new, sub_document_id_old, sub_document_id_new
FROM document_revisions
WHERE id = $1
`

func (q *Queries) GetDocumentRevision(ctx context.Context, id uuid.UUID) (DocumentRevision, error) {
	row := q.db.QueryRowContext(ctx, getDocumentRevision, id)
	var i DocumentRevision
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Explanation,
		&i.DocumentIDOld,
		&i.DocumentIDNew,
		&i.SubDocumentIDOld,
		&i.SubDocumentIDNew,
	)
	return i, err
}

const listDocumentRevisionsByDocument = `-- name: ListDocumentRevisionsByDocument :many
SELECT id, created_at, updated_at, explanation, document_id_old, document_id_new, sub_document_id_old, sub_document_id_new
FROM document_revisions
WHERE document_id_old = $1 OR document_id_new = $1
ORDER BY created_at DESC
`

func (q *Queries) ListDocumentRevisionsByDocument(ctx context.Context, documentIDOld uuid.UUID) ([]DocumentRevision, error) {
	rows, err := q.db.QueryContext(ctx, listDocumentRevisionsByDocument, documentIDOld)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DocumentRevision
	for rows.Next() {
		var i DocumentRevision
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Explanation,
			&i.DocumentIDOld,
			&i.DocumentIDNew,
			&i.SubDocumentIDOld,
			&i.SubDocumentIDNew,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDocumentRevisionsBySubdocument = `-- name: ListDocumentRevisionsBySubdocument :many
SELECT id, created_at, updated_at, explanation, document_id_old, document_id_new, sub_document_id_old, sub_document_id_new
FROM document_revisions
WHERE sub_document_id_old = $1 OR sub_document_id_new = $1
ORDER BY created_at DESC
`

func (q *Queries) ListDocumentRevisionsBySubdocument(ctx context.Context, subDocumentIDOld uuid.UUID) ([]DocumentRevision, error) {
	rows, err := q.db.QueryContext(ctx, listDocumentRevisionsBySubdocument, subDocumentIDOld)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DocumentRevision
	for rows.Next() {
		var i DocumentRevision
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Explanation,
			&i.DocumentIDOld,
			&i.DocumentIDNew,
			&i.SubDocumentIDOld,
			&i.SubDocumentIDNew,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
