// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: keywords.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createKeyword = `-- name: CreateKeyword :one
INSERT INTO keywords (name)
VALUES ($1)
RETURNING id, created_at, updated_at, name
`

func (q *Queries) CreateKeyword(ctx context.Context, name string) (Keyword, error) {
	row := q.db.QueryRowContext(ctx, createKeyword, name)
	var i Keyword
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
	)
	return i, err
}

const deleteKeyword = `-- name: DeleteKeyword :exec
DELETE FROM keywords
WHERE id = $1
`

func (q *Queries) DeleteKeyword(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteKeyword, id)
	return err
}

const getKeyword = `-- name: GetKeyword :one
SELECT id, created_at, updated_at, name
FROM keywords
WHERE id = $1
`

func (q *Queries) GetKeyword(ctx context.Context, id uuid.UUID) (Keyword, error) {
	row := q.db.QueryRowContext(ctx, getKeyword, id)
	var i Keyword
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
	)
	return i, err
}

const getKeywordByName = `-- name: GetKeywordByName :one
SELECT id, created_at, updated_at, name
FROM keywords
WHERE name = $1
`

func (q *Queries) GetKeywordByName(ctx context.Context, name string) (Keyword, error) {
	row := q.db.QueryRowContext(ctx, getKeywordByName, name)
	var i Keyword
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
	)
	return i, err
}

const listKeywords = `-- name: ListKeywords :many
SELECT id, created_at, updated_at, name
FROM keywords
ORDER BY name ASC
`

func (q *Queries) ListKeywords(ctx context.Context) ([]Keyword, error) {
	rows, err := q.db.QueryContext(ctx, listKeywords)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Keyword
	for rows.Next() {
		var i Keyword
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listKeywordsByName = `-- name: ListKeywordsByName :many
SELECT id, created_at, updated_at, name
FROM keywords
WHERE name = $1
ORDER BY created_at ASC
`

func (q *Queries) ListKeywordsByName(ctx context.Context, name string) ([]Keyword, error) {
	rows, err := q.db.QueryContext(ctx, listKeywordsByName, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Keyword
	for rows.Next() {
		var i Keyword
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchKeywords = `-- name: SearchKeywords :many
SELECT id, created_at, updated_at, name
FROM keywords
WHERE name ILIKE '%' || $1 || '%'
ORDER BY name ASC
`

func (q *Queries) SearchKeywords(ctx context.Context, dollar_1 sql.NullString) ([]Keyword, error) {
	rows, err := q.db.QueryContext(ctx, searchKeywords, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Keyword
	for rows.Next() {
		var i Keyword
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateKeyword = `-- name: UpdateKeyword :one
UPDATE keywords
SET name = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, created_at, updated_at, name
`

type UpdateKeywordParams struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
}

func (q *Queries) UpdateKeyword(ctx context.Context, arg UpdateKeywordParams) (Keyword, error) {
	row := q.db.QueryRowContext(ctx, updateKeyword, arg.ID, arg.Name)
	var i Keyword
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
	)
	return i, err
}

const upsertKeywordByName = `-- name: UpsertKeywordByName :one
INSERT INTO keywords (name)
VALUES ($1)
ON CONFLICT (name) DO UPDATE SET updated_at = NOW()
RETURNING id, created_at, updated_at, name
`

func (q *Queries) UpsertKeywordByName(ctx context.Context, name string) (Keyword, error) {
	row := q.db.QueryRowContext(ctx, upsertKeywordByName, name)
	var i Keyword
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
	)
	return i, err
}
