// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: law_changes.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const countRecentLawChanges = `-- name: CountRecentLawChanges :one
SELECT COUNT(*)
FROM law_changes
WHERE created_at >= NOW() - INTERVAL '24 hours'
`

func (q *Queries) CountRecentLawChanges(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countRecentLawChanges)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createLawChange = `-- name: CreateLawChange :one
INSERT INTO law_changes (explanation, law_id_old, law_id_new, sub_law_id_old, sub_law_id_new, old_text, new_text)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, created_at, updated_at, explanation, law_id_old, law_id_new, sub_law_id_old, sub_law_id_new, old_text, new_text
`

type CreateLawChangeParams struct {
	Explanation string    `json:"explanation"`
	LawIDOld    uuid.UUID `json:"law_id_old"`
	LawIDNew    uuid.UUID `json:"law_id_new"`
	SubLawIDOld uuid.UUID `json:"sub_law_id_old"`
	SubLawIDNew uuid.UUID `json:"sub_law_id_new"`
	OldText     string    `json:"old_text"`
	NewText     string    `json:"new_text"`
}

func (q *Queries) CreateLawChange(ctx context.Context, arg CreateLawChangeParams) (LawChange, error) {
	row := q.db.QueryRowContext(ctx, createLawChange,
		arg.Explanation,
		arg.LawIDOld,
		arg.LawIDNew,
		arg.SubLawIDOld,
		arg.SubLawIDNew,
		arg.OldText,
		arg.NewText,
	)
	var i LawChange
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Explanation,
		&i.LawIDOld,
		&i.LawIDNew,
		&i.SubLawIDOld,
		&i.SubLawIDNew,
		&i.OldText,
		&i.NewText,
	)
	return i, err
}

const deleteLawChange = `-- name: DeleteLawChange :exec
DELETE FROM law_changes
WHERE id = $1
`

func (q *Queries) DeleteLawChange(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteLawChange, id)
	return err
}

const deleteLawChangesBetween = `-- name: DeleteLawChangesBetween :exec
DELETE FROM law_changes
WHERE law_id_old = $1 AND law_id_new = $2
`

type DeleteLawChangesBetweenParams struct {
	LawIDOld uuid.UUID `json:"law_id_old"`
	LawIDNew uuid.UUID `json:"law_id_new"`
}

func (q *Queries) DeleteLawChangesBetween(ctx context.Context, arg DeleteLawChangesBetweenParams) error {
	_, err := q.db.ExecContext(ctx, deleteLawChangesBetween, arg.LawIDOld, arg.LawIDNew)
	return err
}

const getLawChange = `-- name: GetLawChange :one
SELECT id, created_at, updated_at, explanation, law_id_old, law_id_new, sub_law_id_old, sub_law_id_new, old_text, new_text
FROM law_changes
WHERE id = $1
`

func (q *Queries) GetLawChange(ctx context.Context, id uuid.UUID) (LawChange, error) {
	row := q.db.QueryRowContext(ctx, getLawChange, id)
	var i LawChange
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Explanation,
		&i.LawIDOld,
		&i.LawIDNew,
		&i.SubLawIDOld,
		&i.SubLawIDNew,
		&i.OldText,
		&i.NewText,
	)
	return i, err
}

const getLawChangesBetween = `-- name: GetLawChangesBetween :many
SELECT id, created_at, updated_at, explanation, law_id_old, law_id_new, sub_law_id_old, sub_law_id_new, old_text, new_text
FROM law_changes
WHERE law_id_old = $1 AND law_id_new = $2
ORDER BY created_at DESC
`

type GetLawChangesBetweenParams struct {
	LawIDOld uuid.UUID `json:"law_id_old"`
	LawIDNew uuid.UUID `json:"law_id_new"`
}

func (q *Queries) GetLawChangesBetween(ctx context.Context, arg GetLawChangesBetweenParams) ([]LawChange, error) {
	rows, err := q.db.QueryContext(ctx, getLawChangesBetween, arg.LawIDOld, arg.LawIDNew)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LawChange
	for rows.Next() {
		var i LawChange
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Explanation,
			&i.LawIDOld,
			&i.LawIDNew,
			&i.SubLawIDOld,
			&i.SubLawIDNew,
			&i.OldText,
			&i.NewText,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLawChangesByLaw = `-- name: ListLawChangesByLaw :many
SELECT id, created_at, updated_at, explanation, law_id_old, law_id_new, sub_law_id_old, sub_law_id_new, old_text, new_text
FROM law_changes
WHERE law_id_old = $1 OR law_id_new = $1
ORDER BY created_at DESC
`

func (q *Queries) ListLawChangesByLaw(ctx context.Context, lawIDOld uuid.UUID) ([]LawChange, error) {
	rows, err := q.db.QueryContext(ctx, listLawChangesByLaw, lawIDOld)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LawChange
	for rows.Next() {
		var i LawChange
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Explanation,
			&i.LawIDOld,
			&i.LawIDNew,
			&i.SubLawIDOld,
			&i.SubLawIDNew,
			&i.OldText,
			&i.NewText,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLawChangesBySublaw = `-- name: ListLawChangesBySublaw :many
SELECT id, created_at, updated_at, explanation, law_id_old, law_id_new, sub_law_id_old, sub_law_id_new, old_text, new_text
FROM law_changes
WHERE sub_law_id_old = $1 OR sub_law_id_new = $1
ORDER BY created_at DESC
`

func (q *Queries) ListLawChangesBySublaw(ctx context.Context, subLawIDOld uuid.UUID) ([]LawChange, error) {
	rows, err := q.db.QueryContext(ctx, listLawChangesBySublaw, subLawIDOld)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LawChange
	for rows.Next() {
		var i LawChange
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Explanation,
			&i.LawIDOld,
			&i.LawIDNew,
			&i.SubLawIDOld,
			&i.SubLawIDNew,
			&i.OldText,
			&i.NewText,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
