// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: law_changes.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createLawChange = `-- name: CreateLawChange :one
INSERT INTO law_changes (explanation, law_id_old, law_id_new, sub_law_id_old, sub_law_id_new)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, created_at, updated_at, explanation, law_id_old, law_id_new, sub_law_id_old, sub_law_id_new
`

type CreateLawChangeParams struct {
	Explanation string    `json:"explanation"`
	LawIDOld    uuid.UUID `json:"law_id_old"`
	LawIDNew    uuid.UUID `json:"law_id_new"`
	SubLawIDOld uuid.UUID `json:"sub_law_id_old"`
	SubLawIDNew uuid.UUID `json:"sub_law_id_new"`
}

func (q *Queries) CreateLawChange(ctx context.Context, arg CreateLawChangeParams) (LawChange, error) {
	row := q.db.QueryRowContext(ctx, createLawChange,
		arg.Explanation,
		arg.LawIDOld,
		arg.LawIDNew,
		arg.SubLawIDOld,
		arg.SubLawIDNew,
	)
	var i LawChange
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Explanation,
		&i.LawIDOld,
		&i.LawIDNew,
		&i.SubLawIDOld,
		&i.SubLawIDNew,
	)
	return i, err
}

const deleteLawChange = `-- name: DeleteLawChange :exec
DELETE FROM law_changes
WHERE id = $1
`

func (q *Queries) DeleteLawChange(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteLawChange, id)
	return err
}

const getLawChange = `-- name: GetLawChange :one
SELECT id, created_at, updated_at, explanation, law_id_old, law_id_new, sub_law_id_old, sub_law_id_new
FROM law_changes
WHERE id = $1
`

func (q *Queries) GetLawChange(ctx context.Context, id uuid.UUID) (LawChange, error) {
	row := q.db.QueryRowContext(ctx, getLawChange, id)
	var i LawChange
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Explanation,
		&i.LawIDOld,
		&i.LawIDNew,
		&i.SubLawIDOld,
		&i.SubLawIDNew,
	)
	return i, err
}

const listLawChangesByLaw = `-- name: ListLawChangesByLaw :many
SELECT id, created_at, updated_at, explanation, law_id_old, law_id_new, sub_law_id_old, sub_law_id_new
FROM law_changes
WHERE law_id_old = $1 OR law_id_new = $1
ORDER BY created_at DESC
`

func (q *Queries) ListLawChangesByLaw(ctx context.Context, lawIDOld uuid.UUID) ([]LawChange, error) {
	rows, err := q.db.QueryContext(ctx, listLawChangesByLaw, lawIDOld)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LawChange
	for rows.Next() {
		var i LawChange
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Explanation,
			&i.LawIDOld,
			&i.LawIDNew,
			&i.SubLawIDOld,
			&i.SubLawIDNew,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLawChangesBySublaw = `-- name: ListLawChangesBySublaw :many
SELECT id, created_at, updated_at, explanation, law_id_old, law_id_new, sub_law_id_old, sub_law_id_new
FROM law_changes
WHERE sub_law_id_old = $1 OR sub_law_id_new = $1
ORDER BY created_at DESC
`

func (q *Queries) ListLawChangesBySublaw(ctx context.Context, subLawIDOld uuid.UUID) ([]LawChange, error) {
	rows, err := q.db.QueryContext(ctx, listLawChangesBySublaw, subLawIDOld)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LawChange
	for rows.Next() {
		var i LawChange
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Explanation,
			&i.LawIDOld,
			&i.LawIDNew,
			&i.SubLawIDOld,
			&i.SubLawIDNew,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
