// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: laws.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createLaw = `-- name: CreateLaw :one
INSERT INTO laws (citation, date_placed, date_replaced)
VALUES ($1, $2, $3)
RETURNING id, created_at, updated_at, citation, date_placed, date_replaced
`

type CreateLawParams struct {
	Citation     string       `json:"citation"`
	DatePlaced   sql.NullTime `json:"date_placed"`
	DateReplaced sql.NullTime `json:"date_replaced"`
}

func (q *Queries) CreateLaw(ctx context.Context, arg CreateLawParams) (Law, error) {
	row := q.db.QueryRowContext(ctx, createLaw, arg.Citation, arg.DatePlaced, arg.DateReplaced)
	var i Law
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Citation,
		&i.DatePlaced,
		&i.DateReplaced,
	)
	return i, err
}

const deleteLaw = `-- name: DeleteLaw :exec
DELETE FROM laws
WHERE id = $1
`

func (q *Queries) DeleteLaw(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteLaw, id)
	return err
}

const getLaw = `-- name: GetLaw :one
SELECT id, created_at, updated_at, citation, date_placed, date_replaced
FROM laws
WHERE id = $1
`

func (q *Queries) GetLaw(ctx context.Context, id uuid.UUID) (Law, error) {
	row := q.db.QueryRowContext(ctx, getLaw, id)
	var i Law
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Citation,
		&i.DatePlaced,
		&i.DateReplaced,
	)
	return i, err
}

const listActiveLaws = `-- name: ListActiveLaws :many
SELECT id, created_at, updated_at, citation, date_placed, date_replaced
FROM laws
WHERE date_replaced IS NULL
ORDER BY citation ASC
`

func (q *Queries) ListActiveLaws(ctx context.Context) ([]Law, error) {
	rows, err := q.db.QueryContext(ctx, listActiveLaws)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Law
	for rows.Next() {
		var i Law
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Citation,
			&i.DatePlaced,
			&i.DateReplaced,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLaws = `-- name: ListLaws :many
SELECT id, created_at, updated_at, citation, date_placed, date_replaced
FROM laws
ORDER BY created_at DESC
`

func (q *Queries) ListLaws(ctx context.Context) ([]Law, error) {
	rows, err := q.db.QueryContext(ctx, listLaws)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Law
	for rows.Next() {
		var i Law
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Citation,
			&i.DatePlaced,
			&i.DateReplaced,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markLawReplaced = `-- name: MarkLawReplaced :one
UPDATE laws
SET date_replaced = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, created_at, updated_at, citation, date_placed, date_replaced
`

type MarkLawReplacedParams struct {
	ID           uuid.UUID    `json:"id"`
	DateReplaced sql.NullTime `json:"date_replaced"`
}

func (q *Queries) MarkLawReplaced(ctx context.Context, arg MarkLawReplacedParams) (Law, error) {
	row := q.db.QueryRowContext(ctx, markLawReplaced, arg.ID, arg.DateReplaced)
	var i Law
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Citation,
		&i.DatePlaced,
		&i.DateReplaced,
	)
	return i, err
}

const searchLawsByCitation = `-- name: SearchLawsByCitation :many
SELECT id, created_at, updated_at, citation, date_placed, date_replaced
FROM laws
WHERE citation ILIKE '%' || $1 || '%'
ORDER BY citation ASC
`

func (q *Queries) SearchLawsByCitation(ctx context.Context, dollar_1 sql.NullString) ([]Law, error) {
	rows, err := q.db.QueryContext(ctx, searchLawsByCitation, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Law
	for rows.Next() {
		var i Law
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Citation,
			&i.DatePlaced,
			&i.DateReplaced,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLaw = `-- name: UpdateLaw :one
UPDATE laws
SET citation = $2, date_placed = $3, date_replaced = $4, updated_at = NOW()
WHERE id = $1
RETURNING id, created_at, updated_at, citation, date_placed, date_replaced
`

type UpdateLawParams struct {
	ID           uuid.UUID    `json:"id"`
	Citation     string       `json:"citation"`
	DatePlaced   sql.NullTime `json:"date_placed"`
	DateReplaced sql.NullTime `json:"date_replaced"`
}

func (q *Queries) UpdateLaw(ctx context.Context, arg UpdateLawParams) (Law, error) {
	row := q.db.QueryRowContext(ctx, updateLaw,
		arg.ID,
		arg.Citation,
		arg.DatePlaced,
		arg.DateReplaced,
	)
	var i Law
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Citation,
		&i.DatePlaced,
		&i.DateReplaced,
	)
	return i, err
}
