// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: subdocuments.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createSubdocument = `-- name: CreateSubdocument :one
INSERT INTO subdocuments (name, document_id, citation, date_placed, date_replaced)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, created_at, updated_at, name, document_id, citation, date_placed, date_replaced
`

type CreateSubdocumentParams struct {
	Name         string       `json:"name"`
	DocumentID   uuid.UUID    `json:"document_id"`
	Citation     string       `json:"citation"`
	DatePlaced   sql.NullTime `json:"date_placed"`
	DateReplaced sql.NullTime `json:"date_replaced"`
}

func (q *Queries) CreateSubdocument(ctx context.Context, arg CreateSubdocumentParams) (Subdocument, error) {
	row := q.db.QueryRowContext(ctx, createSubdocument,
		arg.Name,
		arg.DocumentID,
		arg.Citation,
		arg.DatePlaced,
		arg.DateReplaced,
	)
	var i Subdocument
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.DocumentID,
		&i.Citation,
		&i.DatePlaced,
		&i.DateReplaced,
	)
	return i, err
}

const deleteSubdocument = `-- name: DeleteSubdocument :exec
DELETE FROM subdocuments
WHERE id = $1
`

func (q *Queries) DeleteSubdocument(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteSubdocument, id)
	return err
}

const getSubdocument = `-- name: GetSubdocument :one
SELECT id, created_at, updated_at, name, document_id, citation, date_placed, date_replaced
FROM subdocuments
WHERE id = $1
`

func (q *Queries) GetSubdocument(ctx context.Context, id uuid.UUID) (Subdocument, error) {
	row := q.db.QueryRowContext(ctx, getSubdocument, id)
	var i Subdocument
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.DocumentID,
		&i.Citation,
		&i.DatePlaced,
		&i.DateReplaced,
	)
	return i, err
}

const listActiveSubdocumentsByDocument = `-- name: ListActiveSubdocumentsByDocument :many
SELECT id, created_at, updated_at, name, document_id, citation, date_placed, date_replaced
FROM subdocuments
WHERE document_id = $1 AND date_replaced IS NULL
ORDER BY citation ASC
`

func (q *Queries) ListActiveSubdocumentsByDocument(ctx context.Context, documentID uuid.UUID) ([]Subdocument, error) {
	rows, err := q.db.QueryContext(ctx, listActiveSubdocumentsByDocument, documentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Subdocument
	for rows.Next() {
		var i Subdocument
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Name,
			&i.DocumentID,
			&i.Citation,
			&i.DatePlaced,
			&i.DateReplaced,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubdocumentsByDocument = `-- name: ListSubdocumentsByDocument :many
SELECT id, created_at, updated_at, name, document_id, citation, date_placed, date_replaced
FROM subdocuments
WHERE document_id = $1
ORDER BY citation ASC
`

func (q *Queries) ListSubdocumentsByDocument(ctx context.Context, documentID uuid.UUID) ([]Subdocument, error) {
	rows, err := q.db.QueryContext(ctx, listSubdocumentsByDocument, documentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Subdocument
	for rows.Next() {
		var i Subdocument
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Name,
			&i.DocumentID,
			&i.Citation,
			&i.DatePlaced,
			&i.DateReplaced,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markSubdocumentReplaced = `-- name: MarkSubdocumentReplaced :one
UPDATE subdocuments
SET date_replaced = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, created_at, updated_at, name, document_id, citation, date_placed, date_replaced
`

type MarkSubdocumentReplacedParams struct {
	ID           uuid.UUID    `json:"id"`
	DateReplaced sql.NullTime `json:"date_replaced"`
}

func (q *Queries) MarkSubdocumentReplaced(ctx context.Context, arg MarkSubdocumentReplacedParams) (Subdocument, error) {
	row := q.db.QueryRowContext(ctx, markSubdocumentReplaced, arg.ID, arg.DateReplaced)
	var i Subdocument
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.DocumentID,
		&i.Citation,
		&i.DatePlaced,
		&i.DateReplaced,
	)
	return i, err
}

const searchSubdocuments = `-- name: SearchSubdocuments :many
SELECT id, created_at, updated_at, name, document_id, citation, date_placed, date_replaced
FROM subdocuments
WHERE name ILIKE '%' || $1 || '%' OR citation ILIKE '%' || $1 || '%'
ORDER BY citation ASC
`

func (q *Queries) SearchSubdocuments(ctx context.Context, dollar_1 sql.NullString) ([]Subdocument, error) {
	rows, err := q.db.QueryContext(ctx, searchSubdocuments, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Subdocument
	for rows.Next() {
		var i Subdocument
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Name,
			&i.DocumentID,
			&i.Citation,
			&i.DatePlaced,
			&i.DateReplaced,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSubdocument = `-- name: UpdateSubdocument :one
UPDATE subdocuments
SET name = $2, document_id = $3, citation = $4, date_placed = $5, date_replaced = $6, updated_at = NOW()
WHERE id = $1
RETURNING id, created_at, updated_at, name, document_id, citation, date_placed, date_replaced
`

type UpdateSubdocumentParams struct {
	ID           uuid.UUID    `json:"id"`
	Name         string       `json:"name"`
	DocumentID   uuid.UUID    `json:"document_id"`
	Citation     string       `json:"citation"`
	DatePlaced   sql.NullTime `json:"date_placed"`
	DateReplaced sql.NullTime `json:"date_replaced"`
}

func (q *Queries) UpdateSubdocument(ctx context.Context, arg UpdateSubdocumentParams) (Subdocument, error) {
	row := q.db.QueryRowContext(ctx, updateSubdocument,
		arg.ID,
		arg.Name,
		arg.DocumentID,
		arg.Citation,
		arg.DatePlaced,
		arg.DateReplaced,
	)
	var i Subdocument
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.DocumentID,
		&i.Citation,
		&i.DatePlaced,
		&i.DateReplaced,
	)
	return i, err
}
