// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sublaws.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createSublaw = `-- name: CreateSublaw :one
INSERT INTO sublaws (name, citation, sequence, anchor, content, embedding, keywords, document_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, created_at, updated_at, citation, sequence, anchor, content, embedding, keywords, document_id, name
`

type CreateSublawParams struct {
	Name       sql.NullString `json:"name"`
	Citation   string         `json:"citation"`
	Sequence   sql.NullString `json:"sequence"`
	Anchor     sql.NullString `json:"anchor"`
	Content    sql.NullString `json:"content"`
	Embedding  sql.NullString `json:"embedding"`
	Keywords   sql.NullString `json:"keywords"`
	DocumentID uuid.UUID      `json:"document_id"`
}

func (q *Queries) CreateSublaw(ctx context.Context, arg CreateSublawParams) (Sublaw, error) {
	row := q.db.QueryRowContext(ctx, createSublaw,
		arg.Name,
		arg.Citation,
		arg.Sequence,
		arg.Anchor,
		arg.Content,
		arg.Embedding,
		arg.Keywords,
		arg.DocumentID,
	)
	var i Sublaw
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Citation,
		&i.Sequence,
		&i.Anchor,
		&i.Content,
		&i.Embedding,
		&i.Keywords,
		&i.DocumentID,
		&i.Name,
	)
	return i, err
}

const deleteSublaw = `-- name: DeleteSublaw :exec
DELETE FROM sublaws
WHERE id = $1
`

func (q *Queries) DeleteSublaw(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteSublaw, id)
	return err
}

const deleteSublawsByLaw = `-- name: DeleteSublawsByLaw :exec
DELETE FROM sublaws
WHERE document_id = $1
`

func (q *Queries) DeleteSublawsByLaw(ctx context.Context, documentID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteSublawsByLaw, documentID)
	return err
}

const getSublaw = `-- name: GetSublaw :one
SELECT id, created_at, updated_at, citation, sequence, anchor, content, embedding, keywords, document_id, name
FROM sublaws
WHERE id = $1
`

func (q *Queries) GetSublaw(ctx context.Context, id uuid.UUID) (Sublaw, error) {
	row := q.db.QueryRowContext(ctx, getSublaw, id)
	var i Sublaw
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Citation,
		&i.Sequence,
		&i.Anchor,
		&i.Content,
		&i.Embedding,
		&i.Keywords,
		&i.DocumentID,
		&i.Name,
	)
	return i, err
}

const getSublawByLawAndAnchor = `-- name: GetSublawByLawAndAnchor :one
SELECT id, created_at, updated_at, citation, sequence, anchor, content, embedding, keywords, document_id, name
FROM sublaws
WHERE document_id = $1 AND anchor = $2
`

type GetSublawByLawAndAnchorParams struct {
	DocumentID uuid.UUID      `json:"document_id"`
	Anchor     sql.NullString `json:"anchor"`
}

func (q *Queries) GetSublawByLawAndAnchor(ctx context.Context, arg GetSublawByLawAndAnchorParams) (Sublaw, error) {
	row := q.db.QueryRowContext(ctx, getSublawByLawAndAnchor, arg.DocumentID, arg.Anchor)
	var i Sublaw
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Citation,
		&i.Sequence,
		&i.Anchor,
		&i.Content,
		&i.Embedding,
		&i.Keywords,
		&i.DocumentID,
		&i.Name,
	)
	return i, err
}

const listSublawsByLaw = `-- name: ListSublawsByLaw :many
SELECT id, created_at, updated_at, citation, sequence, anchor, content, embedding, keywords, document_id, name
FROM sublaws
WHERE document_id = $1
ORDER BY sequence ASC NULLS LAST, created_at ASC
`

func (q *Queries) ListSublawsByLaw(ctx context.Context, documentID uuid.UUID) ([]Sublaw, error) {
	rows, err := q.db.QueryContext(ctx, listSublawsByLaw, documentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Sublaw
	for rows.Next() {
		var i Sublaw
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Citation,
			&i.Sequence,
			&i.Anchor,
			&i.Content,
			&i.Embedding,
			&i.Keywords,
			&i.DocumentID,
			&i.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchSublawsContent = `-- name: SearchSublawsContent :many
SELECT id, created_at, updated_at, citation, sequence, anchor, content, embedding, keywords, document_id, name
FROM sublaws
WHERE content ILIKE '%' || $1 || '%'
ORDER BY created_at DESC
`

func (q *Queries) SearchSublawsContent(ctx context.Context, dollar_1 sql.NullString) ([]Sublaw, error) {
	rows, err := q.db.QueryContext(ctx, searchSublawsContent, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Sublaw
	for rows.Next() {
		var i Sublaw
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Citation,
			&i.Sequence,
			&i.Anchor,
			&i.Content,
			&i.Embedding,
			&i.Keywords,
			&i.DocumentID,
			&i.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchSublawsKeywords = `-- name: SearchSublawsKeywords :many
SELECT id, created_at, updated_at, citation, sequence, anchor, content, embedding, keywords, document_id, name
FROM sublaws
WHERE keywords ILIKE '%' || $1 || '%'
ORDER BY created_at DESC
`

func (q *Queries) SearchSublawsKeywords(ctx context.Context, dollar_1 sql.NullString) ([]Sublaw, error) {
	rows, err := q.db.QueryContext(ctx, searchSublawsKeywords, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Sublaw
	for rows.Next() {
		var i Sublaw
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Citation,
			&i.Sequence,
			&i.Anchor,
			&i.Content,
			&i.Embedding,
			&i.Keywords,
			&i.DocumentID,
			&i.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSublaw = `-- name: UpdateSublaw :one
UPDATE sublaws
SET name = $2, citation = $3, sequence = $4, anchor = $5, content = $6, embedding = $7, keywords = $8, document_id = $9, updated_at = NOW()
WHERE id = $1
RETURNING id, created_at, updated_at, citation, sequence, anchor, content, embedding, keywords, document_id, name
`

type UpdateSublawParams struct {
	ID         uuid.UUID      `json:"id"`
	Name       sql.NullString `json:"name"`
	Citation   string         `json:"citation"`
	Sequence   sql.NullString `json:"sequence"`
	Anchor     sql.NullString `json:"anchor"`
	Content    sql.NullString `json:"content"`
	Embedding  sql.NullString `json:"embedding"`
	Keywords   sql.NullString `json:"keywords"`
	DocumentID uuid.UUID      `json:"document_id"`
}

func (q *Queries) UpdateSublaw(ctx context.Context, arg UpdateSublawParams) (Sublaw, error) {
	row := q.db.QueryRowContext(ctx, updateSublaw,
		arg.ID,
		arg.Name,
		arg.Citation,
		arg.Sequence,
		arg.Anchor,
		arg.Content,
		arg.Embedding,
		arg.Keywords,
		arg.DocumentID,
	)
	var i Sublaw
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Citation,
		&i.Sequence,
		&i.Anchor,
		&i.Content,
		&i.Embedding,
		&i.Keywords,
		&i.DocumentID,
		&i.Name,
	)
	return i, err
}
