// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_metadatas.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const addUserKeyword = `-- name: AddUserKeyword :one
INSERT INTO user_metadatas (user_id, keyword)
VALUES ($1, $2)
ON CONFLICT (user_id, keyword) DO UPDATE SET updated_at = NOW()
RETURNING id, created_at, updated_at, user_id, keyword
`

type AddUserKeywordParams struct {
	UserID  uuid.UUID `json:"user_id"`
	Keyword uuid.UUID `json:"keyword"`
}

func (q *Queries) AddUserKeyword(ctx context.Context, arg AddUserKeywordParams) (UserMetadata, error) {
	row := q.db.QueryRowContext(ctx, addUserKeyword, arg.UserID, arg.Keyword)
	var i UserMetadata
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.Keyword,
	)
	return i, err
}

const listUserKeywords = `-- name: ListUserKeywords :many
SELECT user_metadatas.id, user_metadatas.created_at, user_metadatas.updated_at, user_metadatas.user_id, user_metadatas.keyword, keywords.name AS keyword_name
FROM user_metadatas
JOIN keywords ON keywords.id = user_metadatas.keyword
WHERE user_metadatas.user_id = $1
ORDER BY keywords.name ASC
`

type ListUserKeywordsRow struct {
	ID          uuid.UUID `json:"id"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
	UserID      uuid.UUID `json:"user_id"`
	Keyword     uuid.UUID `json:"keyword"`
	KeywordName string    `json:"keyword_name"`
}

func (q *Queries) ListUserKeywords(ctx context.Context, userID uuid.UUID) ([]ListUserKeywordsRow, error) {
	rows, err := q.db.QueryContext(ctx, listUserKeywords, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserKeywordsRow
	for rows.Next() {
		var i ListUserKeywordsRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserID,
			&i.Keyword,
			&i.KeywordName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersByKeyword = `-- name: ListUsersByKeyword :many
SELECT users.id, users.created_at, users.updated_at, users.email, users.hashed_password, users.job_title, users.first_name, users.last_name
FROM user_metadatas
JOIN users ON users.id = user_metadatas.user_id
WHERE user_metadatas.keyword = $1
ORDER BY users.email ASC
`

func (q *Queries) ListUsersByKeyword(ctx context.Context, keyword uuid.UUID) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listUsersByKeyword, keyword)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Email,
			&i.HashedPassword,
			&i.JobTitle,
			&i.FirstName,
			&i.LastName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeAllUserKeywords = `-- name: RemoveAllUserKeywords :exec
DELETE FROM user_metadatas
WHERE user_id = $1
`

func (q *Queries) RemoveAllUserKeywords(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, removeAllUserKeywords, userID)
	return err
}

const removeUserKeyword = `-- name: RemoveUserKeyword :exec
DELETE FROM user_metadatas
WHERE user_id = $1 AND keyword = $2
`

type RemoveUserKeywordParams struct {
	UserID  uuid.UUID `json:"user_id"`
	Keyword uuid.UUID `json:"keyword"`
}

func (q *Queries) RemoveUserKeyword(ctx context.Context, arg RemoveUserKeywordParams) error {
	_, err := q.db.ExecContext(ctx, removeUserKeyword, arg.UserID, arg.Keyword)
	return err
}
